/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderRouteImport } from './routes/order'
import { Route as TrackRouteImport } from './routes/track'
import { Route as UpgradesRouteImport } from './routes/upgrades'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutActivityRouteImport } from './routes/admin/_layout/activity'
import { Route as AdminLayoutBlockedUsersRouteImport } from './routes/admin/_layout/blocked-users'
import { Route as AdminLayoutContactRouteImport } from './routes/admin/_layout/contact'
import { Route as AdminLayoutCustomersRouteImport } from './routes/admin/_layout/customers'
import { Route as AdminLayoutFaqRouteImport } from './routes/admin/_layout/faq'
import { Route as AdminLayoutFormsRouteImport } from './routes/admin/_layout/forms'
import { Route as AdminLayoutHomepageRouteImport } from './routes/admin/_layout/homepage'
import { Route as AdminLayoutMediaRouteImport } from './routes/admin/_layout/media'
import { Route as AdminLayoutNotificationsRouteImport } from './routes/admin/_layout/notifications'
import { Route as AdminLayoutPlayersRouteImport } from './routes/admin/_layout/players'
import { Route as AdminLayoutSecurityRouteImport } from './routes/admin/_layout/security'
import { Route as AdminLayoutServicesRouteImport } from './routes/admin/_layout/services'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutOrdersIndexRouteImport } from './routes/admin/_layout/orders.index'
import { Route as AdminLayoutOrdersOrderIdRouteImport } from './routes/admin/_layout/orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradesRoute = UpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutActivityRoute = AdminLayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBlockedUsersRoute = AdminLayoutBlockedUsersRouteImport.update({
  id: '/blocked-users',
  path: '/blocked-users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContactRoute = AdminLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCustomersRoute = AdminLayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutFaqRoute = AdminLayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutFormsRoute = AdminLayoutFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutHomepageRoute = AdminLayoutHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMediaRoute = AdminLayoutMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutNotificationsRoute =
  AdminLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPlayersRoute = AdminLayoutPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSecurityRoute = AdminLayoutSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutServicesRoute = AdminLayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrdersIndexRoute = AdminLayoutOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrdersOrderIdRoute =
  AdminLayoutOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/upgrades': typeof UpgradesRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/activity': typeof AdminLayoutActivityRoute
  '/admin/blocked-users': typeof AdminLayoutBlockedUsersRoute
  '/admin/contact': typeof AdminLayoutContactRoute
  '/admin/customers': typeof AdminLayoutCustomersRoute
  '/admin/faq': typeof AdminLayoutFaqRoute
  '/admin/forms': typeof AdminLayoutFormsRoute
  '/admin/homepage': typeof AdminLayoutHomepageRoute
  '/admin/media': typeof AdminLayoutMediaRoute
  '/admin/notifications': typeof AdminLayoutNotificationsRoute
  '/admin/players': typeof AdminLayoutPlayersRoute
  '/admin/security': typeof AdminLayoutSecurityRoute
  '/admin/services': typeof AdminLayoutServicesRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/orders/$orderId': typeof AdminLayoutOrdersOrderIdRoute
  '/admin/orders/': typeof AdminLayoutOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/upgrades': typeof UpgradesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/activity': typeof AdminLayoutActivityRoute
  '/admin/blocked-users': typeof AdminLayoutBlockedUsersRoute
  '/admin/contact': typeof AdminLayoutContactRoute
  '/admin/customers': typeof AdminLayoutCustomersRoute
  '/admin/faq': typeof AdminLayoutFaqRoute
  '/admin/forms': typeof AdminLayoutFormsRoute
  '/admin/homepage': typeof AdminLayoutHomepageRoute
  '/admin/media': typeof AdminLayoutMediaRoute
  '/admin/notifications': typeof AdminLayoutNotificationsRoute
  '/admin/players': typeof AdminLayoutPlayersRoute
  '/admin/security': typeof AdminLayoutSecurityRoute
  '/admin/services': typeof AdminLayoutServicesRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/orders/$orderId': typeof AdminLayoutOrdersOrderIdRoute
  '/admin/orders': typeof AdminLayoutOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/upgrades': typeof UpgradesRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_layout/activity': typeof AdminLayoutActivityRoute
  '/admin/_layout/blocked-users': typeof AdminLayoutBlockedUsersRoute
  '/admin/_layout/contact': typeof AdminLayoutContactRoute
  '/admin/_layout/customers': typeof AdminLayoutCustomersRoute
  '/admin/_layout/faq': typeof AdminLayoutFaqRoute
  '/admin/_layout/forms': typeof AdminLayoutFormsRoute
  '/admin/_layout/homepage': typeof AdminLayoutHomepageRoute
  '/admin/_layout/media': typeof AdminLayoutMediaRoute
  '/admin/_layout/notifications': typeof AdminLayoutNotificationsRoute
  '/admin/_layout/players': typeof AdminLayoutPlayersRoute
  '/admin/_layout/security': typeof AdminLayoutSecurityRoute
  '/admin/_layout/services': typeof AdminLayoutServicesRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/orders/$orderId': typeof AdminLayoutOrdersOrderIdRoute
  '/admin/_layout/orders/': typeof AdminLayoutOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/track'
    | '/upgrades'
    | '/admin'
    | '/admin/login'
    | '/admin/activity'
    | '/admin/blocked-users'
    | '/admin/contact'
    | '/admin/customers'
    | '/admin/faq'
    | '/admin/forms'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/players'
    | '/admin/security'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order'
    | '/track'
    | '/upgrades'
    | '/admin/login'
    | '/admin/activity'
    | '/admin/blocked-users'
    | '/admin/contact'
    | '/admin/customers'
    | '/admin/faq'
    | '/admin/forms'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/players'
    | '/admin/security'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/orders/$orderId'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/order'
    | '/track'
    | '/upgrades'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/_layout/activity'
    | '/admin/_layout/blocked-users'
    | '/admin/_layout/contact'
    | '/admin/_layout/customers'
    | '/admin/_layout/faq'
    | '/admin/_layout/forms'
    | '/admin/_layout/homepage'
    | '/admin/_layout/media'
    | '/admin/_layout/notifications'
    | '/admin/_layout/players'
    | '/admin/_layout/security'
    | '/admin/_layout/services'
    | '/admin/_layout/settings'
    | '/admin/_layout/users'
    | '/admin/_layout/'
    | '/admin/_layout/orders/$orderId'
    | '/admin/_layout/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRoute
  TrackRoute: typeof TrackRoute
  UpgradesRoute: typeof UpgradesRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/activity': {
      id: '/admin/_layout/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminLayoutActivityRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/blocked-users': {
      id: '/admin/_layout/blocked-users'
      path: '/blocked-users'
      fullPath: '/admin/blocked-users'
      preLoaderRoute: typeof AdminLayoutBlockedUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/contact': {
      id: '/admin/_layout/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminLayoutContactRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/customers': {
      id: '/admin/_layout/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminLayoutCustomersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/faq': {
      id: '/admin/_layout/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminLayoutFaqRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/forms': {
      id: '/admin/_layout/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminLayoutFormsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/homepage': {
      id: '/admin/_layout/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminLayoutHomepageRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/media': {
      id: '/admin/_layout/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminLayoutMediaRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/notifications': {
      id: '/admin/_layout/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminLayoutNotificationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/players': {
      id: '/admin/_layout/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminLayoutPlayersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/security': {
      id: '/admin/_layout/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminLayoutSecurityRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/services': {
      id: '/admin/_layout/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminLayoutServicesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders/': {
      id: '/admin/_layout/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminLayoutOrdersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders/$orderId': {
      id: '/admin/_layout/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminLayoutOrdersOrderIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutActivityRoute: typeof AdminLayoutActivityRoute
  AdminLayoutBlockedUsersRoute: typeof AdminLayoutBlockedUsersRoute
  AdminLayoutContactRoute: typeof AdminLayoutContactRoute
  AdminLayoutCustomersRoute: typeof AdminLayoutCustomersRoute
  AdminLayoutFaqRoute: typeof AdminLayoutFaqRoute
  AdminLayoutFormsRoute: typeof AdminLayoutFormsRoute
  AdminLayoutHomepageRoute: typeof AdminLayoutHomepageRoute
  AdminLayoutMediaRoute: typeof AdminLayoutMediaRoute
  AdminLayoutNotificationsRoute: typeof AdminLayoutNotificationsRoute
  AdminLayoutPlayersRoute: typeof AdminLayoutPlayersRoute
  AdminLayoutSecurityRoute: typeof AdminLayoutSecurityRoute
  AdminLayoutServicesRoute: typeof AdminLayoutServicesRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutOrdersOrderIdRoute: typeof AdminLayoutOrdersOrderIdRoute
  AdminLayoutOrdersIndexRoute: typeof AdminLayoutOrdersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutActivityRoute: AdminLayoutActivityRoute,
  AdminLayoutBlockedUsersRoute: AdminLayoutBlockedUsersRoute,
  AdminLayoutContactRoute: AdminLayoutContactRoute,
  AdminLayoutCustomersRoute: AdminLayoutCustomersRoute,
  AdminLayoutFaqRoute: AdminLayoutFaqRoute,
  AdminLayoutFormsRoute: AdminLayoutFormsRoute,
  AdminLayoutHomepageRoute: AdminLayoutHomepageRoute,
  AdminLayoutMediaRoute: AdminLayoutMediaRoute,
  AdminLayoutNotificationsRoute: AdminLayoutNotificationsRoute,
  AdminLayoutPlayersRoute: AdminLayoutPlayersRoute,
  AdminLayoutSecurityRoute: AdminLayoutSecurityRoute,
  AdminLayoutServicesRoute: AdminLayoutServicesRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutOrdersOrderIdRoute: AdminLayoutOrdersOrderIdRoute,
  AdminLayoutOrdersIndexRoute: AdminLayoutOrdersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRoute,
  TrackRoute: TrackRoute,
  UpgradesRoute: UpgradesRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
